version: '3.9'
services:
  db:
    image: postgres:14.4-alpine
    restart: always
    network_mode: "host"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - network:/var/lib/postgresql/data
#  movies:
#    image: movies-service:latest
#    restart: always
#    network_mode: "host"
#    environment:
#      - MOVIES_DATABASE_URL=localhost:5432
#    ports:
#      - '8080:8080'
volumes:
  db:
    driver: local